# Generated by Django 4.1.13 on 2024-01-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_content_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='descrition',
            new_name='description',
        ),
    ]
